# Generated by Django 4.2.3 on 2023-07-10 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=350)),
                ('description', models.TextField()),
                ('price', models.FloatField()),
                ('image', models.FileField(upload_to='')),
            ],
        ),
    ]
